// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.3
// source: bbm/bomber/bomber.proto

package bomber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BomberScriptDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BomberScriptDetailRequest) Reset() {
	*x = BomberScriptDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bbm_bomber_bomber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BomberScriptDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomberScriptDetailRequest) ProtoMessage() {}

func (x *BomberScriptDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbm_bomber_bomber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomberScriptDetailRequest.ProtoReflect.Descriptor instead.
func (*BomberScriptDetailRequest) Descriptor() ([]byte, []int) {
	return file_bbm_bomber_bomber_proto_rawDescGZIP(), []int{0}
}

func (x *BomberScriptDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BomberScriptDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int64                   `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Code       string                  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Data       *BomberScriptDetailData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BomberScriptDetailResponse) Reset() {
	*x = BomberScriptDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bbm_bomber_bomber_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BomberScriptDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomberScriptDetailResponse) ProtoMessage() {}

func (x *BomberScriptDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbm_bomber_bomber_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomberScriptDetailResponse.ProtoReflect.Descriptor instead.
func (*BomberScriptDetailResponse) Descriptor() ([]byte, []int) {
	return file_bbm_bomber_bomber_proto_rawDescGZIP(), []int{1}
}

func (x *BomberScriptDetailResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BomberScriptDetailResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BomberScriptDetailResponse) GetData() *BomberScriptDetailData {
	if x != nil {
		return x.Data
	}
	return nil
}

type BomberScriptDetailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CnName        string  `protobuf:"bytes,3,opt,name=cn_name,json=cnName,proto3" json:"cn_name,omitempty"`
	Description   string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPrivate     string  `protobuf:"bytes,5,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Content       string  `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Databases     []int64 `protobuf:"varint,7,rep,packed,name=databases,proto3" json:"databases,omitempty"`
	UserId        int64   `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Variates      string  `protobuf:"bytes,9,opt,name=variates,proto3" json:"variates,omitempty"`
	SystemCommand string  `protobuf:"bytes,10,opt,name=system_command,json=systemCommand,proto3" json:"system_command,omitempty"` //是否是系统命令
	Account       string  `protobuf:"bytes,11,opt,name=account,proto3" json:"account,omitempty"`
	Version       string  `protobuf:"bytes,12,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *BomberScriptDetailData) Reset() {
	*x = BomberScriptDetailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bbm_bomber_bomber_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BomberScriptDetailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomberScriptDetailData) ProtoMessage() {}

func (x *BomberScriptDetailData) ProtoReflect() protoreflect.Message {
	mi := &file_bbm_bomber_bomber_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomberScriptDetailData.ProtoReflect.Descriptor instead.
func (*BomberScriptDetailData) Descriptor() ([]byte, []int) {
	return file_bbm_bomber_bomber_proto_rawDescGZIP(), []int{2}
}

func (x *BomberScriptDetailData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BomberScriptDetailData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BomberScriptDetailData) GetCnName() string {
	if x != nil {
		return x.CnName
	}
	return ""
}

func (x *BomberScriptDetailData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BomberScriptDetailData) GetIsPrivate() string {
	if x != nil {
		return x.IsPrivate
	}
	return ""
}

func (x *BomberScriptDetailData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BomberScriptDetailData) GetDatabases() []int64 {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *BomberScriptDetailData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BomberScriptDetailData) GetVariates() string {
	if x != nil {
		return x.Variates
	}
	return ""
}

func (x *BomberScriptDetailData) GetSystemCommand() string {
	if x != nil {
		return x.SystemCommand
	}
	return ""
}

func (x *BomberScriptDetailData) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BomberScriptDetailData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_bbm_bomber_bomber_proto protoreflect.FileDescriptor

var file_bbm_bomber_bomber_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x62, 0x6d, 0x2f, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x62, 0x6f, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x6f, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x2b, 0x0a, 0x19, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x85,
	0x01, 0x0a, 0x1a, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xde, 0x02, 0x0a, 0x16, 0x42, 0x6f, 0x6d, 0x62, 0x65,
	0x72, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x65, 0x0a, 0x06, 0x42, 0x6f, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x5b, 0x0a, 0x12, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x2e, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72,
	0x2e, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15,
	0x5a, 0x13, 0x2e, 0x2f, 0x62, 0x62, 0x6d, 0x2f, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x3b, 0x62,
	0x6f, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bbm_bomber_bomber_proto_rawDescOnce sync.Once
	file_bbm_bomber_bomber_proto_rawDescData = file_bbm_bomber_bomber_proto_rawDesc
)

func file_bbm_bomber_bomber_proto_rawDescGZIP() []byte {
	file_bbm_bomber_bomber_proto_rawDescOnce.Do(func() {
		file_bbm_bomber_bomber_proto_rawDescData = protoimpl.X.CompressGZIP(file_bbm_bomber_bomber_proto_rawDescData)
	})
	return file_bbm_bomber_bomber_proto_rawDescData
}

var file_bbm_bomber_bomber_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bbm_bomber_bomber_proto_goTypes = []interface{}{
	(*BomberScriptDetailRequest)(nil),  // 0: bomber.BomberScriptDetailRequest
	(*BomberScriptDetailResponse)(nil), // 1: bomber.BomberScriptDetailResponse
	(*BomberScriptDetailData)(nil),     // 2: bomber.BomberScriptDetailData
}
var file_bbm_bomber_bomber_proto_depIdxs = []int32{
	2, // 0: bomber.BomberScriptDetailResponse.data:type_name -> bomber.BomberScriptDetailData
	0, // 1: bomber.Bomber.BomberScriptDetail:input_type -> bomber.BomberScriptDetailRequest
	1, // 2: bomber.Bomber.BomberScriptDetail:output_type -> bomber.BomberScriptDetailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bbm_bomber_bomber_proto_init() }
func file_bbm_bomber_bomber_proto_init() {
	if File_bbm_bomber_bomber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bbm_bomber_bomber_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BomberScriptDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bbm_bomber_bomber_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BomberScriptDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bbm_bomber_bomber_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BomberScriptDetailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bbm_bomber_bomber_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bbm_bomber_bomber_proto_goTypes,
		DependencyIndexes: file_bbm_bomber_bomber_proto_depIdxs,
		MessageInfos:      file_bbm_bomber_bomber_proto_msgTypes,
	}.Build()
	File_bbm_bomber_bomber_proto = out.File
	file_bbm_bomber_bomber_proto_rawDesc = nil
	file_bbm_bomber_bomber_proto_goTypes = nil
	file_bbm_bomber_bomber_proto_depIdxs = nil
}
